[package]
name = "space_invaders"
version = "0.1.0"
edition = "2021"

[profiles.release]
opt-level = 3
lto = true
debug = false

[dependencies]
bevy = "0.5.0"
# use older winit version to fix crate conflicts.
winit = "0.24.0"
image = "0.23.14"
