[package]
name = "space_invaders"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.5"
rand = "0.8.4"
ron = "0.7.0"
serde = "1.0.131"
tokio = "1.14.0"
anyhow = "1.0.51"
tracing = "0.1.29"
discord-sdk = "0.2.1"
